// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/alter-ego-what-if/CurrentScenario.tsx": () => import("../components/mockups/alter-ego-what-if/CurrentScenario.tsx")
};
